### ISSUE TITLE
需要安装教程

### ISSUE THREAD

**Issue by gh030119** [guojiaxing1995/docker-manager#13]
项目挺好的，界面也行，但是对于我一个萌新来说，没有安装教程我看着就像没看一样，想用又不会用

**Comment by gh030119** [comment]
当我没说，有部署教程但是，能不能出一个详细教程呢

**Comment by guojiaxing1995** [comment]
更新了文档，增加了部署说明和调试运行说明。
部署中有问题可以邮件我： 302802003@qq.com
